/**
 * Human- and PR-friendly rendering of diff/run results.
 */
import type { DiffResult, RunReport, StepChange } from "./types.js";

function truncate(value: unknown, max = 80): string {
  const s = typeof value === "string" ? value : JSON.stringify(value);
  if (s === undefined) return "undefined";
  return s.length > max ? s.slice(0, max - 1) + "…" : s;
}

function renderStepChange(c: StepChange): string[] {
  const lines: string[] = [];
  if (c.kind === "added") {
    lines.push(`  + step[${c.index}] added tool call: ${c.tool}`);
  } else if (c.kind === "removed") {
    lines.push(`  - step[${c.index}] removed tool call: ${c.tool}`);
  } else {
    if (c.toolRenamed) {
      lines.push(
        `  ~ step[${c.index}] tool renamed: ${c.previousTool} -> ${c.tool}`,
      );
    } else {
      lines.push(`  ~ step[${c.index}] tool ${c.tool} args changed:`);
    }
    for (const d of c.argDiffs ?? []) {
      lines.push(
        `      ${d.path}: ${truncate(d.before)} -> ${truncate(d.after)}`,
      );
    }
  }
  return lines;
}

/** Renders a single diff as plain text (used by the CLI). */
export function renderDiffText(diff: DiffResult): string {
  if (diff.isNew) {
    return `NEW    ${diff.scenario}  (no stored snapshot)`;
  }
  if (diff.pass) {
    return `PASS   ${diff.scenario}`;
  }

  const lines: string[] = [`FAIL   ${diff.scenario}  (${diff.mode} mode)`];
  for (const c of diff.stepChanges) {
    lines.push(...renderStepChange(c));
  }
  if (diff.inputDiff) {
    lines.push(
      `  ~ input changed: ${truncate(diff.inputDiff.before)} -> ${truncate(diff.inputDiff.after)}`,
    );
  }
  if (diff.outputDiff) {
    lines.push(
      `  ~ finalOutput changed:`,
      `      before: ${truncate(diff.outputDiff.before, 120)}`,
      `      after:  ${truncate(diff.outputDiff.after, 120)}`,
    );
  }
  return lines.join("\n");
}

/** Renders a full run report as plain text. */
export function renderReportText(report: RunReport): string {
  const lines: string[] = [];
  for (const r of report.results) {
    lines.push(renderDiffText(r.diff));
  }
  lines.push("");
  lines.push(
    `agentcheck: ${report.passed} passed, ${report.failed} failed, ${report.results.length} total`,
  );
  lines.push(report.ok ? "RESULT: PASS" : "RESULT: FAIL");
  return lines.join("\n");
}

function mdEscape(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/** Renders a GitHub-PR-comment-style markdown summary. */
export function renderReportMarkdown(report: RunReport): string {
  const status = report.ok ? "PASS" : "FAIL";
  const emoji = report.ok ? "white_check_mark" : "x";
  const lines: string[] = [];
  lines.push(`## agentcheck — :${emoji}: ${status}`);
  lines.push("");
  lines.push(
    `**${report.passed} passed**, **${report.failed} failed** of ${report.results.length} scenarios.`,
  );
  lines.push("");
  lines.push("| Scenario | Result | Details |");
  lines.push("| --- | --- | --- |");
  for (const { diff } of report.results) {
    let result: string;
    let details: string;
    if (diff.isNew) {
      result = ":new:";
      details = "no stored snapshot — run `agentcheck update`";
    } else if (diff.pass) {
      result = ":white_check_mark:";
      details = "matches snapshot";
    } else {
      result = ":x:";
      const parts: string[] = [];
      const added = diff.stepChanges.filter((c) => c.kind === "added").length;
      const removed = diff.stepChanges.filter((c) => c.kind === "removed").length;
      const changed = diff.stepChanges.filter((c) => c.kind === "changed").length;
      if (added) parts.push(`${added} added`);
      if (removed) parts.push(`${removed} removed`);
      if (changed) parts.push(`${changed} changed`);
      if (diff.outputDiff) parts.push("output changed");
      if (diff.inputDiff) parts.push("input changed");
      details = parts.join(", ") || "differs";
    }
    lines.push(`| ${mdEscape(diff.scenario)} | ${result} | ${mdEscape(details)} |`);
  }

  const failing = report.results.filter((r) => !r.diff.pass && !r.diff.isNew);
  if (failing.length > 0) {
    lines.push("");
    lines.push("<details><summary>Diff details</summary>");
    lines.push("");
    lines.push("```diff");
    for (const r of failing) {
      lines.push(renderDiffText(r.diff));
    }
    lines.push("```");
    lines.push("");
    lines.push("</details>");
  }

  lines.push("");
  lines.push("<sub>Generated by [agentcheck](https://github.com/Viprasol-Tech/agentcheck) · Viprasol Tech</sub>");
  return lines.join("\n");
}
